### ISSUE TITLE
Maybe a tip

### ISSUE THREAD

**Issue by richelbilderbeek** [jorn600/howyouwantitiwantitcoffeesmellinggood#7]
Great that you can get the list of windows!

At the 
[testing_cpp_gui_applications_tutorial I have a script called get_dialog_id](https://github.com/richelbilderbeek/testing_cpp_gui_applications_tutorial/blob/master/scripts/get_dialog_id.sh) to extract the ID of a window.

Perhaps this may be of use to you.

Good luck :+1:

**Comment by JornPrengerFormeel** [comment]
how do i use it?

**Comment by richelbilderbeek** [comment]
You got it to work!
